### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by francescjaume** [travelgateX/go-jwt-tools#14]
Remember to update README.md whenever necessary, due to package update or functionality addition.

**Comment by guzmanthegood** [comment]
Hi @zechao , it's important to update the documentation explaining the use of the library, if important changes have been added such as a jwt parser and a cache, explain how to implement it and examples of use.

**Comment by guzmanthegood** [comment]
Last commit solves this issue, thx @pperaltaisern 

https://github.com/travelgateX/go-jwt-tools/commit/38302142b796095dd57d0a77172e1e39daa1a453
